### ISSUE TITLE
My Game Crashed

### ISSUE THREAD

**Issue by DJMahirNationTV** [Sol-Client/client#82]
## Description (please fill in)
A description of the problem that is occurring.
## Steps to Reproduce
1. What did you do...
2. ...to crash the game?
## Details
Running Sol Client v1.8.2 with OptiFine 1.8.9 HD U M5 on Windows.
## Logs/Crash Report

[Game Log on Hastebin](https://www.toptal.com/developers/hastebin/kubeqozogu.txt)

**Comment by DJMahirNationTV** [comment]
If GameLog is gone:

```
[21:36:39] [main/INFO]: Loading tweak class name io.github.solclient.client.tweak.Tweaker
[21:36:39] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: io.github.solclient.client.tweak.Tweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by HyptexPvP** [comment]
Can we actually know how to reproduce lol.

**Comment by DJMahirNationTV** [comment]
> Can we actually know how to reproduce lol.

But whats the error?

**Comment by HyptexPvP** [comment]
All im guessing is that you don't have the tweaker. Can't say much since I don't have any information

**Comment by DJMahirNationTV** [comment]
> All im guessing is that you don't have the tweaker. Can't say much since I don't have any information

O i see what you mean, how can i enable the "Tweaker" or do have i download something to run it?
